### ISSUE TITLE
TODO: Some API features/bugs

### ISSUE THREAD

**Issue by zerosum0x0** [zerosum0x0/koadic#94]
Thanks to @TheNaterz for creating awesome API. Here's a few things that we can do to improve it.

- [x] Running just `api` with no args should print the help
- [x] Errors while binding a port (such as a low port and getting `PermissionError: [Errno 13] Permission denied`) still say that the API server started correctly (`[+] Rest server running on port 940`)
- [x] API should default to binding to localhost interface, and not 0.0.0.0
- [x] Need option for TLS certificates when binding to 0.0.0.0
- [x] Put some docs in the ~~README~~ Wiki

Ref #80

**Comment by TheNaterz** [comment]
Knocked out the first 3 with https://github.com/zerosum0x0/koadic/commit/7ed480883af87d01f016427cddadd9ab86822f1e

**Comment by TheNaterz** [comment]
Koadic API defaults binding to localhost. Use --remote to bind the API to 0.0.0.0. Use --cert path/to/cert and --key path/to/key to enable TLS when used with --remote. If --remote is not used, --cert and --key do nothing.

**Comment by TheNaterz** [comment]
Documentation has been added as a Wiki page: https://github.com/zerosum0x0/koadic/wiki/REST-API

**Comment by TheNaterz** [comment]
5 up, 5 down. Reopen for more goodness.
